# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = cpp_qt_charts
DESTDIR = ../Debug
CONFIG += debug
LIBS += -L"."
PRECOMPILED_HEADER = stdafx.h
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
QT += charts
include(cpp_qt_charts.pri)
win32:RC_FILE = cpp_qt_charts.rc
